# Generated by Django 5.1.1 on 2024-10-08 17:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=255)),
                ('gender', models.CharField(choices=[('LK', 'Laki-laki'), ('PR', 'Perempuan')], max_length=2)),
                ('born_date', models.DateField()),
                ('visit_date', models.DateTimeField(auto_now_add=True)),
                ('symptom', models.TextField()),
                ('nurse_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
