# Generated by Django 5.1.1 on 2024-10-13 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0003_alter_patient_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='nurse_name',
        ),
    ]
